name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies core
        run: |
          cd packages/easy-email-core && pnpm install

      - name: Run tests core
        run: pnpm run test:core

      - name: Install dependencies extensions
        run: |
          cd packages/easy-email-extensions && pnpm install

      - name: Run tests extensions
        run: pnpm run test:extensions
